name: "Linear Labeler"
description: "GitHub Action to update Linear labels based on the branch name"
inputs:
  branchName:
    required: true
    description: "The name of the branch to add labels to"
  labelNames:
    required: true
    description: "Comma-separated names of the labels to add to the ticket"
  linearApiKey:
    required: true
    description: "Linear API key"
runs:
  using: "node16"
  main: "dist/index.js"